### PR TITLE
Teacher Portal improvement v1.1

### PR DESCRIPTION
**Pull request by 1orZero**
- Optimize Share message list 
- Fix image flickering issue (to be confirmed)
- Add sort by name / create at time
- Add item per page customization on share message list
- Spread the tag list on share message filter

### CODE REVIEW

**Comment by 1orZero** [comment]
I can't test the functionality on the staging site properly due to high database latency. It's unusually high at the moment.

**Comment by 1orZero** [comment]
I extended the statement timeout to 15 seconds for both Production and Staging. 
The slowdown is caused by the exact count query, but its necessary for pagination calculation.

**Comment by 1orZero** [comment]
@thejackwu Good to go! I cleared all student submission records in the staging database. Some records may need to be re-added for testing.

**Comment by thejackwu** [comment]
Looking good! Just couple things to fix: @1orZero 
Screenshot 2024-04-10 15 27 58

1. Translation 
2. Can we change the border color to match the Tag 1C button's border color?
3. Fix overlapping Chinese character

**Comment by 1orZero** [comment]
@thejackwu Fixed!

**Comment by thejackwu** [comment]
One more bug then good to go! @1orZero 
Currently selecting/de-selecting tags will caused a section refresh


https://github.com/exploratortech/chat-everywhere/assets/4432048/f9afae61-0ba1-46ba-b9b8-56dde283d8b8

**Comment by 1orZero** [comment]
@thejackwu  Fixed!

**Comment by 1orZero** [comment]
One more thing: 
- [x] remember to run the new migrations on production when you merge. 
@thejackwu

**Pull request merged**
