### PR TITLE
Teacher Prompt Improvement

### PR DESCRIPTION
**Pull request by 1orZero**
# Prompt  Improvement

- [x] System prompt will now override the system prompt
	- [x] In AI painter mode, only the teacher prompt has the option to provide a system prompt, which will be added to the default system prompt.
	
- [x] Change the default click on a teacher prompt should trigger with its selected default mode.
	- [x] Add first user message field, to the teacher prompt model
	- [x] Provide the default first user message ("Provide a very short welcome message based on your prompt, the role your are playing is based on the prompt.")

- [x] Teacher account being able to see the Teacher Prompt in their end

- [x] Add simple zod validation to the Teacher prompt form

- [ ] Run migration on Production by @thejackwu

### CODE REVIEW

**Comment by 1orZero** [comment]
Ready to review! @thejackwu

**Comment by thejackwu** [comment]
@1orZero Seems like the first message is not being sent? only the system prompt is being triggered?


https://github.com/exploratortech/chat-everywhere/assets/4432048/e616942e-cc76-4702-af71-7539cff888e6

**Comment by 1orZero** [comment]
Ahhh I see, yeah its just not being displayed. It may confuse user. Let me show the first message to the user as well.

**Comment by 1orZero** [comment]
@thejackwu All fixed!

**Review by thejackwu — APPROVED** [review]

**Pull request merged**
