### PR TITLE
[DO-NOT-MERGE] Fix mobile space left behind when mobile keyboard is hidden

### PR DESCRIPTION
**Pull request by williamtriinh**

### CODE REVIEW

**Comment by patel-rushi** [comment]
hey @williamtriinh Will, works better! I found a case in which that space still remain. Replication steps for iPhone users:
1. Tap message box to open keyboard


2. Press pointing-up "<" on iPhone keyboard (locate on top-left in the keyboard window). 

3. The previous step will open up the language selector: 


4. Click outside and that space still remains:

**Comment by patel-rushi** [comment]
lol..didn't expect those screenshots to be enlarged

**Comment by williamtriinh** [comment]
> hey @williamtriinh Will, works better! I found a case in which that space still remain. Replication steps for iPhone users:
> 
>     1. Tap message box to open keyboard
>        
> 
>     2. Press pointing-up "<" on iPhone keyboard (locate on top-left in the keyboard window).
> 
>     3. The previous step will open up the language selector:
>        
> 
>     4. Click outside and that space still remains:
>        

I'll take a look

**Comment by williamtriinh** [comment]
@patel-rushi What about now?

**Comment by patel-rushi** [comment]
Works perfect! @williamtriinh

**Review by patel-rushi — APPROVED** [review]

**Review by 1orZero — COMMENTED** [review]
I tested both the production site and the preview site deployed on Vercel, but I couldn't reproduce the bug.

However, the preview site has some strange scroll-to-bottom issues that only appear in Safari. When I scroll to the top, it automatically scrolls down to the bottom.

It's strange that Chrome (iOS) works well, given that I thought it used Safari as its base on iOS.

**Comment by 1orZero** [comment]
https://github.com/exploratortech/chat-everywhere/assets/53516684/601f1dcb-20f8-439b-a3ab-5ac5b1d3c16b

This is the production site, works fine for me

**Comment by 1orZero** [comment]
https://github.com/exploratortech/chat-everywhere/assets/53516684/452059ea-f517-421f-b94c-0eae058b5e23


The preview site produce empty space on the bottom

**Comment by williamtriinh** [comment]
@1orZero Oh yeah there's some scrolling issues on IOS that I overlooked. On the other hand, the empty space is not fixable based off the research I've done or requires a very hacky, convoluted solution. But, I'll keep looking into it.

**Comment by thejackwu** [comment]
No longer an issue. Closing this PR.

**Pull request closed without merging**
