### PR TITLE
minimize the number of items in left Sidebar Menu

### PR DESCRIPTION
**Pull request by 1orZero**
- Add new Setting model
- RWD support
- Fix top bar weird behaviour 

Now we have maximum 5 menu items at the bottom-left 

I am thinking to move "usage & credit" and "referral program" into the settings model.
Do you think its a good idea?

### CODE REVIEW

**Comment by 1orZero** [comment]
desktop view
mobile view

Preview of desktop and mobile view

**Comment by 1orZero** [comment]
- [ ] Add i18n translation

**Comment by 1orZero** [comment]
copilot:all

**Comment by 1orZero** [comment]
- Minimize the size of the Facebook icon.
- Update the size of the sidebar icons in mobile view.
- Add a maximum width to the pricing table.

**Review by thejackwu — APPROVED** [review]

**Pull request merged**
