### PR TITLE
Teacher portal v0.3 - improvement

### PR DESCRIPTION
**Pull request by 1orZero**
- [x] Optimize Loading (spinner)
- [x] Add a setting option on teacher portal to clear conversation on logout 
- [x] Add an option to hide default characters on Student's account 

- [x] Run migration on Production by @thejackwu

### CODE REVIEW

**Comment by thejackwu** [comment]
The new loading bar is solid! But I found 2 things that ain't great for user experience. 
1. The loading bar seems to show during periodic fetch. Which it not ideal since the teacher wouldn't know that's that for
2. Quite a bug delay between click on the side button and seeing the page change. Is it possible to chance the page first, then load the content after?

 

https://github.com/exploratortech/chat-everywhere/assets/4432048/09ea5421-191f-4840-b1eb-ac492479ea4e

**Comment by 1orZero** [comment]
Fixed!

**Comment by thejackwu** [comment]
@1orZero Working great! Just found one more bug, the `.../zh/teacher-portal` doesn't seems to work. Looks like it is not able to switch to Chinese

**Comment by 1orZero** [comment]
@thejackwu  Fixed! The issue is caused by the accidental removal of the `getServerSideProps` and the missing implementation of `getServerSideProps` in the new sub-routes of the teacher portal.

**Review by thejackwu — APPROVED** [review]

**Pull request merged**
