### PR TITLE
Will/20230606 orderable folders

### PR DESCRIPTION
**Pull request by williamtriinh**
Add the ability to re-order the folders. I went with an indexing approach, where each folder is given a number starting from 100 and increasing by 100 each time. When a folder is reordered, its rank gets updated depending on where it was moved to in the list:
- If inserted at the top of the list, the rank is half the value of the bottom folder's rank (rounded down if decimals exist)
- If inserted anywhere in the middle, the rank is the floored average of the adjacent folders
- If inserted at the end, the rank is 100 more than the last folder's rank

When there's no more space to insert a folder at the start/middle, the ranks needs to be re-balanced, which just set all the ranks to factors of 100 while maintaining the order.

### CODE REVIEW

**Comment by 1orZero** [comment]
It seems like the **orderable folders** feature is not working in the preview site.

Could you please let me know if I am testing this incorrectly? 😂
Or is there something that I am missing?

Below is a video clip from my end.


https://github.com/exploratortech/chat-everywhere/assets/53516684/6bd7e445-06fe-43da-8de9-1311a03e5224

**Comment by thejackwu** [comment]
@1orZero 

I think it only works on Prompt manager, but not the conversation history actually.


https://github.com/exploratortech/chat-everywhere/assets/4432048/2b369352-3ad6-4beb-b684-c7e8f8719650

**Comment by williamtriinh** [comment]
My mistake, I didn't even consider the conversation history because I forgot there were folders there too. I only had it working for prompt folders.

**Comment by williamtriinh** [comment]
@1orZero @thejackwu do you mind trying again now?

**Comment by thejackwu** [comment]
@williamtriinh Works great! Just some minor touchups.
1. Text will get highlighted sometime after moving the folder around. 

https://github.com/exploratortech/chat-everywhere/assets/4432048/25dfa899-1e59-40d9-bd20-cb5dfa8aec7e

2. Would be great if we can have some sort of indicator on where the folder will goes. Like above or below from another folder that I an hovering on.

**Comment by williamtriinh** [comment]
@thejackwu Fixed the styling

**Comment by 1orZero** [comment]
Deleting the Conversation folder is not working. It seems that the react-transition-group package is the main cause. 
I would suggest removing the package and reimplementing the animation from scratch later in another PR.
What do you think?
@williamtriinh @thejackwu

**Review by 1orZero — DISMISSED** [review]
Deleting the Conversation folder is not working. It seems that the react-transition-group package is the main cause.
I would suggest removing the package and reimplementing the animation from scratch later in another PR.
What do you think?
@williamtriinh @thejackwu

**Comment by williamtriinh** [comment]
> Deleting the Conversation folder is not working. It seems that the react-transition-group package is the main cause. I would suggest removing the package and reimplementing the animation from scratch later in another PR. What do you think? @williamtriinh @thejackwu

Sounds like a good idea. I'll try and fix issue and if the animations are gone, we could just implement them again later.

**Comment by thejackwu** [comment]
@williamtriinh Sorry if this is too much to ask for. I am thinking if we already made the Prompt folder orderable, is it possible to make everything orderable? (Conversation, conversation folder, prompt, prompt folder)?

**Comment by williamtriinh** [comment]
> @williamtriinh Sorry if this is too much to ask for. I am thinking if we already made the Prompt folder orderable, is it possible to make everything orderable? (Conversation, conversation folder, prompt, prompt folder)?

Yup, I can definitely make everything orderable.

**Comment by thejackwu** [comment]
Thanks!

-
Jack Wu | CEO at Explorator Labs

**Comment by patel-rushi** [comment]
Hey @williamtriinh Will, good work on orderable folders! Few things I wanted to point out:

1. Improving drag & drop animation: From a user POV, it is difficult to spot that the reordering works due to the current animation. Check out video. Feel free to skip if you think it's not necessary!
2. A bug in "New folders" in prompts sidenav. Check out video.

https://www.loom.com/share/95534abf6a104440879eaeaa4cbec038?sid=1eda4c9a-5efa-4d2a-bbc9-656c1fa7fd78

Doing some more testing. I'll make additional comment, if I find something is broken. Good work!

**Comment by williamtriinh** [comment]
> Hey @williamtriinh Will, good work on orderable folders! Few things I wanted to point out:
> 
>     1. Improving drag & drop animation: From a user POV, it is difficult to spot that the reordering works due to the current animation. Check out video. Feel free to skip if you think it's not necessary!
> 
>     2. A bug in "New folders" in prompts sidenav. Check out video.
> 
> 
> https://www.loom.com/share/95534abf6a104440879eaeaa4cbec038?sid=1eda4c9a-5efa-4d2a-bbc9-656c1fa7fd78
> 
> Doing some more testing. I'll make additional comment, if I find something is broken. Good work!

I made the changes.

**Comment by patel-rushi** [comment]
Looks awesome @williamtriinh !

**Comment by patel-rushi** [comment]
One last little thing I noticed William, is about editing a conversation name. If someone forgets to click the 'tick' button and creates a new conversation, the edited name changes go away. Is it possible to keep the focus (with tick and cross) on that conversation, if the 'tick' button is not pressed?

**Review by patel-rushi — APPROVED** [review]

**Comment by williamtriinh** [comment]
> One last little thing I noticed William, is about editing a conversation name. If someone forgets to click the 'tick' button and creates a new conversation, the edited name changes go away. Is it possible to keep the focus (with tick and cross) on that conversation, if the 'tick' button is not pressed?

I think it's doable. It'll likely take a bit of work so I think it should be done it's own PR.

**Comment by thejackwu** [comment]
@williamtriinh I updated this PR to merge into `chat-everywhere` directly, but there's a merge conflict now.

**Review by thejackwu — APPROVED** [review]

**Pull request merged**
