### PR TITLE
Will/20231003 promocode not working

### PR DESCRIPTION
**Pull request by williamtriinh**
- Use regular console logs for logging errors because Azure's App Insights doesn't seem to work with backend code.
- Make referral code redemption case insensitive.
- Log user's input attempt, and log valid referral codes

### CODE REVIEW

**Comment by thejackwu** [comment]
Seems like if I enter a wrong promo code locally, and only have one edu account. I can a log like this?

Screenshot 2023-10-19 13 26 09

**Comment by williamtriinh** [comment]
> Seems like if I enter a wrong promo code locally, and only have one edu account. I can a log like this?
> Screenshot 2023-10-19 13 26 09

Should be fixed now

**Comment by thejackwu** [comment]
@williamtriinh Sorry getting back to you this late on this, since we've switched to PostHog for tracking, can we use that instead of AppInsight. Ill also give you access to that in a bit. 

The tracking function for PostHog is in `utils/app/eventTracking.ts`

**Comment by thejackwu** [comment]
Also I am adding a 2 weeks promo code mechanism into the app, which shouldn't interfere with your code.

**Pull request closed without merging**
