### PR TITLE
[PENDING] Custom Instruction 

### PR DESCRIPTION
**Pull request by 1orZero**
New feature Custom Instruction

- can be enabled in the Prompt section

Screenshot 2024-02-03 at 10 17 34 PM

- added indicator inside the conversation if its enabled

Screenshot 2024-02-03 at 10 19 47 PM

Task left to do:

- [x] Improve Mobile experience when editing / viewing the custom instruction

### CODE REVIEW

**Comment by 1orZero** [comment]
Hey @thejackwu, Could you review this PR and see where else needs improvements, apart from the Mobile Experience?

**Comment by thejackwu** [comment]
@1orZero Nice UI! Can we make the custom instructions the top items of the list instead of a separate section? I don't want to make the landing dialog too long too complex

Screenshot 2024-02-05 16 34 33

And it's working great overall! 
Screenshot 2024-02-05 16 33 46

**Comment by thejackwu** [comment]
> @1orZero Nice UI! Can we make the custom instructions the top items of the list instead of a separate section? I don't want to make the landing dialog too long too complex
> 
> Screenshot 2024-02-05 16 34 33
> 
> And it's working great overall! Screenshot 2024-02-05 16 33 46

Looking great! Only this is missing for now, where moving the Custom instruction into the same list but at the top of the pre-defined characters.

**Comment by 1orZero** [comment]
> > @1orZero Nice UI! Can we make the custom instructions the top items of the list instead of a separate section? I don't want to make the landing dialog too long too complex
> > Screenshot 2024-02-05 16 34 33
> > And it's working great overall! Screenshot 2024-02-05 16 33 46
> 
> Looking great! Only this is missing for now, where moving the Custom instruction into the same list but at the top of the pre-defined characters.

Done! Its ready now!

**Review by thejackwu — APPROVED** [review]

**Comment by thejackwu** [comment]
@1orZero Approved! But can we merge this along with Teacher portal v0.2? So I can do a big test before releasing?

**Comment by 1orZero** [comment]
@thejackwu I will keep this PR open until the new Teacher Portal PR is ready!

**Pull request merged**
