### PR TITLE
Allow teacher to update student name in the active student account list 

### PR DESCRIPTION
**Pull request by 1orZero**
This pull request adds an API endpoint and a React component for updating student names. The API endpoint allows teachers to update the name of a student in the database, and the React component provides a user interface for editing student names.

### CODE REVIEW

**Comment by 1orZero** [comment]
Ready to review @thejackwu, but the Staging Supabase database still has some issues.

**Comment by thejackwu** [comment]
@1orZero Got it! The staging issue maybe related to this migration on Supabases side.
https://github.com/orgs/supabase/discussions/22135

**Comment by thejackwu** [comment]
@1orZero Working great! Just need to add Chinese translation to the toast.

Screenshot 2024-04-10 15 38 45

**Comment by 1orZero** [comment]
@thejackwu Fixed !

**Review by thejackwu — APPROVED** [review]

**Pull request merged**
