### PR TITLE
Ai Painter improvement

### PR DESCRIPTION
**Pull request by 1orZero**

### CODE REVIEW

**Comment by 1orZero** [comment]
@thejackwu: Fallback endpoint added. The dalle_1 endpoint is currently commented out until fixed (resource not found). 

Implemented logic: After 3 retries, switch to OpenAI endpoint instead of Azure.

**Comment by 1orZero** [comment]
There is a bug in the staging site. The image is not displayed after a successful generation.

**Comment by 1orZero** [comment]
Fixed the Vercel edge is terminated sometimes due to insufficient streaming buffer

**Comment by 1orZero** [comment]
@thejackwu: Fallback endpoint added. The dalle_1 endpoint is currently commented out until fixed (resource not found).

Implemented logic: After 3 retries, switch to OpenAI endpoint instead of Azure.
Implemented a logic to keep the connection alive.

Ready to review!

**Comment by thejackwu** [comment]
@1orZero I updated the `chat-everywhere` branch to have the backup DallE endpoints, as well as using OpenAI for speed on AI painter mode and image compression (to 500x500). Do you mind merging that into this branch, but keep the download button the full resolution?

**Comment by 1orZero** [comment]
Done! 
@thejackwu 
But the Image optimization only works on the local and production sites.

Image Resizing is currently enabled for [Pro plan and above](https://supabase.com/pricing).
Reference:
https://supabase.com/docs/guides/storage/serving/image-transformations

**Comment by thejackwu** [comment]
@1orZero Yepp! I updated the code to only use image compression on local and prod. But when I was testing it locally, I noticed some flickering, also in the Network tab you can see the image is being fetched multiple times. 


https://github.com/exploratortech/chat-everywhere/assets/4432048/1b896b6b-d187-4154-8a4b-a6949d8f3202

**Comment by 1orZero** [comment]
Hey @thejackwu , I couldn't reproduce the flickering or multiple image fetching issues. However, I have optimized the component. Could you try it out and see if the issue is resolved?

**Review by thejackwu — APPROVED** [review]

**Pull request merged**
