### PR TITLE
Derek/20230710-mj-image-gen-improvement

### PR DESCRIPTION
**Pull request by 1orZero**
- Add zoom-out option
- Add Upscale option
- Add Make Variations option
- Add new styled progress bar

### CODE REVIEW

**Comment by 1orZero** [comment]
Ready to merge!

**Comment by thejackwu** [comment]
@1orZero Works great! Can we update the Notion doc to indicate what each button do? Let's also add a (?) button under the at the bottom of the image message to open up that doc in-app. So user can know how they work

**Comment by thejackwu** [comment]
https://github.com/exploratortech/chat-everywhere/assets/4432048/1e39651c-8843-420b-9e56-a8c508b233f8

Can we also make it collapse when click as well?

**Comment by 1orZero** [comment]
- [x] improve toggle for completed progress bar
- [x] remove the number from image selection button
- [x] Update notion doc
- [x] Add a (?) button on the top right of the MJ image component, which will open up the AI image feature page.

**Comment by 1orZero** [comment]
@thejackwu Its ready!

**Comment by thejackwu** [comment]
@1orZero Works great on Desktop! But couple UX improvements:
1. On mobile, the buttons are oversize. (attached screen recording)
2. When I tab on the image, I would accidentally clicked on the buttons.
3. While the image is being generated, perhaps we should disable the image buttons, so user won't be able to click on any until the generation is completed.
4. Can we also add some more example of what each button do on our Notion Doc? So user can know what does each button mean.


https://github.com/exploratortech/chat-everywhere/assets/4432048/31089344-f3a1-4b57-9449-ce03db6133c0

**Comment by 1orZero** [comment]
I have updated how the buttons are shown. Previously, they were displayed on hover, but I couldn't find a good solution for mobile layout. So, I have changed the logic to display the buttons on click.

- [x]  Fix issue with buttons being easily misclicked in mobile layout.
- [x]  Fix issue with oversized buttons.
- [x]  Disable buttons when image is being generated.
- [x]  Add a detailed example to the Notion document.

**Comment by 1orZero** [comment]
Its ready to test! @thejackwu

**Review by thejackwu — APPROVED** [review]

**Pull request merged**
