### PR TITLE
Optimize the message rendering

### PR DESCRIPTION
**Pull request by 1orZero**
Currently, when a conversation has too many messages, the page re-renders with every change.

The PR has a dependency on https://github.com/exploratortech/chat-everywhere/pull/210

TODO:

- [x] the message component that is not in the user's viewport should not be rendered.

### CODE REVIEW

**Comment by 1orZero** [comment]
now most message component will be rendered only once, unless the message has changed.

@thejackwu Please le me now if this helped to reduce the laggy issue.

**Comment by thejackwu** [comment]
@1orZero It's working! It no longer re-render when typing in the text box!

Before:

https://github.com/exploratortech/chat-everywhere/assets/4432048/2d757171-90a6-4d11-96cb-c24f3765e016

After:

https://github.com/exploratortech/chat-everywhere/assets/4432048/fbbcdcf7-9d88-454c-958c-7cae62975e69

**Comment by thejackwu** [comment]
Can we take it one step further, making it not re-render previous messages while streaming?


https://github.com/exploratortech/chat-everywhere/assets/4432048/8e83c40d-e741-4c82-86ff-28b32894ea8d

**Comment by 1orZero** [comment]
Yeah! Also i m trying to implement not rendering the components unless they in the user's viewport. Those are what i am going to do next!

**Comment by 1orZero** [comment]
@thejackwu I have integrated the new package we discussed in the meeting for the chat message list. It is now smoother than ever.


I just need to fix the following bug

- [x] - Auto scrolling to the end 
- [x] - Show scroll to the end button

**Comment by thejackwu** [comment]
> @thejackwu I have integrated the new package we discussed in the meeting for the chat message list. It is now smoother than ever.
> 
> I just need to fix the following bug
> 
> * [x]  - Auto scrolling to the end
> * [x]  - Show scroll to the end button

Woo it's so smooth! Can't wait for the rest to complete then roll it out!!

**Comment by 1orZero** [comment]
Should be fixed!

**Comment by thejackwu** [comment]
I was testing it for a bit on Mobile, seems like it will keep scroll back to the bottom during streaming, I couldn't make it stay by trying to scroll back up.

**Comment by 1orZero** [comment]
I noticed there are 2 behaviors.

- [x]	When the user is at the bottom, the chat scrolls automatically to show new messages.
- [x]	When the user is not at the bottom, they can scroll anywhere in the chat.

I will have this fixed later today

**Comment by 1orZero** [comment]
Hey @thejackwu  can you test the following functionality for me? 
-  When the user is at the bottom, the chat automatically scrolls to show new messages.
-  When the user is not at the bottom, they can scroll anywhere in the chat.

Currently, this workaround isn't perfect. There seems to be a delay in rendering the old chat history when the user scrolls to an old message while new messages are streaming. 
Let me know if this is acceptable.

**Comment by thejackwu** [comment]
@1orZero So far seems like the point 1 is not working quite well. Even when I at at the bottom, but it's not automatically following the new message. 


https://github.com/exploratortech/chat-everywhere/assets/4432048/6b78a868-8f72-4e78-8ca3-93dd981f73d3

**Comment by 1orZero** [comment]
@thejackwu Yeah, I'm thinking the same. Let's see if I can find a better solution.

**Comment by 1orZero** [comment]
@thejackwu DONE UPDATE! Now should be good to go!

**Review by thejackwu — APPROVED** [review]

**Comment by thejackwu** [comment]
@1orZero Good to merge! It was working great, I love it!
I was trying to merge #210 first, but there are some merge conflict, I assume we can just merge this one in instead?

**Pull request merged**
